### ISSUE TITLE
[Bug] Alpha versions SHOULD NOT required upgrade

### ISSUE THREAD

**Issue by TinyChou** [hxfdarling/a8k#20]
**Describe the bug**
As title described.

**To Reproduce**
1. Go to using a8k in terminal;
2. type 'k'
4. See

![image](https://user-images.githubusercontent.com/4263842/58815647-92d32300-865a-11e9-9e71-5fbebc337250.png)

**Expected behavior**
Alpha versions or version under developing SHOULD NOT alert users to upgrade.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser: No
 - Version [1.8.5]

**Additional context**
No additional context.

**Comment by TinyChou** [comment]
Alphas or betas, testing versions, version under developing either should be count.

**Comment by TinyChou** [comment]
Like may helps:
https://semver.org/#spec-item-11

**Comment by hxfdarling** [comment]
Ok，I will fix it.

在 2019年6月4日，00:54，Tiny Chou <notifications@github.com<mailto:notifications@github.com>> 写道：


Describe the bug
As title described.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to using a8k in terminal;
  2.  type 'k'
  3.  See

[image]<https://user-images.githubusercontent.com/4263842/58815647-92d32300-865a-11e9-9e71-5fbebc337250.png>

Expected behavior
Alpha versions or version under developing SHOULD NOT alert users to upgrade.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: macOS Mojave 10.14.5
  *   Browser: No
  *   Version [1.8.5]

Additional context
No additional context.
